version: "3.4"

services:
  client:
    container_name: bike-app-3
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000

networks:
  default:
    external: true
    name: bike
